### ISSUE TITLE
Support for custom Guice Injectors

### ISSUE THREAD

**Issue by segfly** [xvik/dropwizard-guicey#1]
Unlike https://github.com/HubSpot/dropwizard-guice I do not see an easy way to install a custom injector to support guice extensions like: https://github.com/Netflix/governator

Was this intentional or am I missing something in the docs?

Thanks.

**Comment by xvik** [comment]
Regarding pmd config change: single exception shouldn't affect rules for entire application, so I revert pmd config.
Budle class now marked with suppress annotation (suppress only size check). Such annotation clearly marks class as exceptional from general rules and later these suppressions could be easily reviewed (sometimes pmd is wrong and annotation could stay forever).

**Comment by segfly** [comment]
I create a detailed article on leveraging this feature with Governator: https://github.com/xvik/dropwizard-guicey/wiki/Governator-Integration

**Comment by xvik** [comment]
Thank you! great contribution! :) already put link in readme
There is a gitter chat link on main page you can contact me there (in some cases it could be faster than issues :))
