### ISSUE TITLE
Automatic-Module-Name provided is Invalid

### ISSUE THREAD

**Issue by sdqali** [xvik/dropwizard-guicey#106]
Thank you for all your great work on Dropwizard Guicey. 

We ran in to this issue while migrating to JDK 11.

### How to reproduce

```
$ wget "https://repo1.maven.org/maven2/ru/vyarus/dropwizard-guicey/5.0.1/dropwizard-guicey-5.0.1.jar"

$ jar --version
jar 11.0.3

$ jar --describe-module --file dropwizard-guicey-5.0.1.jar
Unable to derive module descriptor for: dropwizard-guicey-5.0.1.jar
Automatic-Module-Name: dropwizard-guicey.core: Invalid module name: 'dropwizard-guicey' is not a Java identifier
```

The character `-` is not a valid character to be present in a module name.

**Comment by xvik** [comment]
Oh! I should have checked the spec! Thank you!

**Comment by sdqali** [comment]
@xvik I am happy to submit a PR to address this. We could pick one of two approaches:

- Remove the explicit `Automatic-Module-Name` which will force Java to infer a module name and it does a good job of inferring a module name.
- Change value of `Automatic-Module-Name` to something like `xvik.dropwizard.guicey`.

Which approach do you prefer?

**Comment by xvik** [comment]
I want to preserve an explicit module name (explicit always better). 
It should be "ru.vyarus.dropwizard.guicey".
And ext modules would become then (for example) "ru.vyarus.dropwizard.guicey.eventbus".

This way name will not match base package [as recommended](https://blog.joda.org/2017/04/java-se-9-jpms-module-naming.html) (for both projects), but close enough. More importantly, it preserves the relation between projects.

If you know any side effects of such naming please tell me: I never used modules and unlikely to be in the near future, so I will simply not face problems myself.

**Comment by sdqali** [comment]
Your recommendation of `ru.vyarus.dropwizard.guicey` sounds like the right thing. I will change the PR.

**Comment by sdqali** [comment]
PR - https://github.com/xvik/dropwizard-guicey/pull/107
