### ISSUE TITLE
Conditionally register managed 

### ISSUE THREAD

**Issue by IgorBerman** [xvik/dropwizard-guicey#11]
Hi
not a bug, but rather a question:
Can I somehow register Managed object as function of some configuration param?
Can you provide some example?
Thanks in advance

**Comment by xvik** [comment]
Hi
Do you want to register managed object only in some cases? 
Can you please tell me more detailed use-case?

Default [managed installer](https://github.com/xvik/dropwizard-guicey/blob/master/src/main/java/ru/vyarus/dropwizard/guice/module/installer/feature/ManagedInstaller.java) installs beans which implement Managed. But you can disable it and add your own installer (with custom logic). I can suggest something, but need to understand your case first.

And you can always register managed manually (pure dropwizard way).

**Comment by IgorBerman** [comment]
Hi,
thanks for the suggestion
I've managed to do this with pure dropwizard way while taking guice injector from guicebundle
I mean I wanted to create instance from guice injector so all autowiring will happen


```
	private GuiceBundle<MyConfig> guiceBundle;
	@Override
	public String getName() {
		return "aaa";
	}

	@Override
	public void initialize(Bootstrap<MyConfig> bootstrap) {
		guiceBundle = GuiceBundle.<MyConfig> builder()
				.installers(...)
				.extensions(...)
				.modules(...)
				.build();
		bootstrap.addBundle(guiceBundle);
	}

	@Override
	public void run(MyConfig configuration, Environment environment) {
		if (configuration.getAppConfig().isStartBatch()) {
			MyManaged managed = guiceBundle.getInjector().getInstance(MyManaged.class);
			environment.lifecycle().manage(managed);
		} else {
			log.warn("MyManaged won't be registered");
		}
	}
```

**Comment by xvik** [comment]
You can reference injector statically inside application class (or when you have app instance):
```java
InjectorLookup.getInjector(this).get().getInstance(MyManaged.class)
```
Not sure if its the best way for you, but your managed could be always registered and simply do nothing on start, if configuration doesn't require it.

```java
public class MyManaged implements Managed {
  @Inject
  private MyConfig config;

  public void start() throws Exception {
      if (!config.getAppConfig().isStartBatch()){
           log.warn("MyManaged won't start");
           return;
      }
  }
}
```

**Comment by IgorBerman** [comment]
@xvik , this was my first idea, however I prefer to do the setup in module only, otherwise code in other places in MyManaged(besides start) should also condition on this flag which becomes kind of polluted.

thanks for the help!
