### ISSUE TITLE
Guicey's configuration hook fails for some integration tests only

### ISSUE THREAD

**Issue by liriarte** [xvik/dropwizard-guicey#111]
We are using `Dropwizard-Guicey` and `Testcointainers` for integrations tests. We use a hook to override a provider, so we can use a DynamoDB instance provided by Testcointainers for integrations tests.

It works well for all tests individually, but when we run all the test together some of them seem to ignore the hook, trying to use a local instance of Dynamo and failing. It seems that there is some kind of race condition.

We register the hook on each integration test as follows:

```
static {
        new TestHook().register();
    }
```

Is there anything missing or wrong? Please help.

**Comment by xvik** [comment]
Static block executed just after class loading, which makes it useless in case of multiple tests. Besides, guicey clears used hooks after hooks appliance (and so reset provider for further tests).

For junit 4 there is a [special rule](http://xvik.github.io/dropwizard-guicey/5.1.0/guide/test/junit4/#customizing-guicey-configuration) for proper hooks registration.

For junit 5 hooks may be specified [inside extension annotation or as class field](http://xvik.github.io/dropwizard-guicey/5.1.0/guide/test/junit5/#application-test-modification)

Spock [behaves the same as junit 5](http://xvik.github.io/dropwizard-guicey/5.1.0/guide/test/spock/#application-test-modification)

**Comment by liriarte** [comment]
Many thanks for the advice! 

It looks like `GuiceyHooksRule` is only available with v5 and dropwizard v2, isn't it? Is there any other way to apply the hook consistently for all integration tests without updating the version?

If the static block is present on each test class, shouldn't guicey apply the hook every time anyway, if it clears them out first?

**Comment by xvik** [comment]
> It looks like GuiceyHooksRule is only available with v5 and dropwizard v2, isn't it? Is there any other way to apply the hook consistently for all integration tests without updating the version?

Hooks rule was added in 4.2.0 but it was called [GuiceyConfigurationRule](http://xvik.github.io/dropwizard-guicey/4.2.0/guide/test/#customizing-guicey-configuration). Also, pay attention that you'll have to use `RuleChain` to properly order junit rules.

> If the static block is present on each test class, shouldn't guicey apply the hook every time anyway, even if it clears them out first?

The static initialization block is executed just after class loading. It would work in some cases, but generally, it's very fragile as test class could be loaded long before its execution (you can't actually control lifecycle). 

If you want something simple and common for all tests, you can simply override application:

```java
class TestApplication extend MyApplication {
         @Override
         public void initialize(Bootstrap bootstrap) {
                 new TestHook().register();
                 super.initialize(bootstrap);
         }
}
```

Here hook will always be registered at the correct point

**Comment by liriarte** [comment]
Many thanks for all the advise! `GuiceyConfigurationRule` did the trick!

`new GuiceyConfigurationRule((builder) -> builder.modulesOverride(new TestModule()))`
