### ISSUE TITLE
Guicey JDBI extension - forDbi function is expecting V2 DBI class

### ISSUE THREAD

**Issue by levyshachar2** [xvik/dropwizard-guicey#112]
Hi , I'm trying to use Guicey JDBI extension to enable us to use @InTransaction annotation.
I looked at the documentation , and I'm trying to use a custom Jdbi such as
.bundles(JdbiBundle.forDbi((conf, env) -> dataAccessModule.prepareJdbi(env, ((Configuration) conf))))

whereas prepareJdbi returns Jdbi object.

will there be support for V3 Jdbi classes?
something like JdbiBundle.forJdbi...

Thank you!

**Comment by xvik** [comment]
Hi!
Probably you're using [JDBI2](http://xvik.github.io/dropwizard-guicey/5.1.0/extras/jdbi/) module instead of [JDBI3](http://xvik.github.io/dropwizard-guicey/5.1.0/extras/jdbi3/).

If not (and correct module used), please clarify what is "V3 Jdbi classes"?

**Comment by levyshachar2** [comment]
Hi @xvik , you were right, I was using the JDBI2 Module, Thank you and sorry.
