### ISSUE TITLE
dropwizard 1.0.0

### ISSUE THREAD

**Issue by brackxm** [xvik/dropwizard-guicey#12]
support dropwizard 1.0.0
hk2 guice-bridge to be upgraded

**Comment by xvik** [comment]
I will do one more release for 0.9.3 before.
I checked with dw 1.0-RC2 and there were no problems at all, so it should not take much time to prepare next (compatible) release.
Most likely, both releases will happen in a few days.

**Comment by sheldon-sminq** [comment]
That would be great.

**Comment by xvik** [comment]
Status update: just released [3.3.0](https://github.com/xvik/dropwizard-guicey/releases/tag/3.3.0) - last release for 0.9.

**Comment by xvik** [comment]
Snapshot version for dropwizard 1.0 may be used through [jitpack](https://jitpack.io/#xvik/dropwizard-guicey).
I plan to add few changes before release (small breaking), but it should not take much time. Hopefully, new version will be released early next week.

**Comment by ekarlso** [comment]
Any updates on this?

**Comment by xvik** [comment]
I'm trying to do all breaking changes in this release so it will be 4.0.0. This and lack of time was the main reasons for delays.
Currently, I plan to release in two days, but, looking to my "predictions" above, I'm scared to promise this) Anyway, I do my best to release sooner.

By the way, if anyone wants to propose some breaking change or have feedback about diagnostic introduced in the last version (or any other feedback) now is the best time to tell me.

**Comment by xvik** [comment]
It's [released](https://github.com/xvik/dropwizard-guicey/releases/tag/4.0.0)!
Thank you all for patience and understanding!

p.s. come to new [guicey google group](https://groups.google.com/forum/#!forum/dropwizard-guicey)
