### ISSUE TITLE
Conditionally inject @WebFilter

### ISSUE THREAD

**Issue by mustafashabib** [xvik/dropwizard-guicey#120]
Hello

I have a a `WebFilter` that Guicey injects automatically - however, I'd like to use a configuration to determine if it should be injected rather than have it automatically picked up. Is there an example of how to do this?

Thanks as always

**Comment by xvik** [comment]
Hello!

Extensions registered during the initialization phase when the configuration is not available yet, so it is not possible to register extension conditionally. But, you can disable extensions at the runtime phase based on configuration (which is essentially the same as optional registration).

[Here is an example](http://xvik.github.io/dropwizard-guicey/5.1.0/decomposition/#optional-extensions).

**Comment by mustafashabib** [comment]
Thank you, that will work.
