### ISSUE TITLE
Remove Logback classic dependency

### ISSUE THREAD

**Issue by sirianni** [xvik/dropwizard-guicey#127]
Is it possible to remove the `logback-classic` dependency on `TargetLengthBasedClassNameAbbreviator`?

We are binding SLF4J to log4j2 in our application and having logback-classic also on the classpath causes issues with the [SLF4J binding](http://slf4j.org/manual.html#swapping) behavior.

**Comment by xvik** [comment]
Oh, yes, of course. It is used only for console reporting and I can simply copy the abbreviator implementation from there.

**Comment by xvik** [comment]
[Released](http://xvik.github.io/dropwizard-guicey/5.2.0/about/release-notes/)
