### ISSUE TITLE
Guice 5 (beta) compatibility

### ISSUE THREAD

**Issue by gjvoosten** [xvik/dropwizard-guicey#135]
On our application with Java 15 we're seeing these errors:
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/…/.gradle/caches/modules-2/files-2.1/com.google.inject/guice/4.2.3/2ea992d6d7bdcac7a43111a95d182a4c42eb5ff7/guice-4.2.3.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```
According to https://github.com/google/guice/issues/1133 this is fixed in 5.0.0-BETA-1 so it'd be nice if at some point you could update (I can fully understand if you wish to wait for an official non-beta v5 release).
Release information is here:https://github.com/google/guice/wiki/Guice500

**Comment by xvik** [comment]
I updated the master to guice 5. There was only one problem: guice internal stopwatch class (used by guicey) was renamed which will make guice version downgrade impossible (but, hopefully, it won't be a problem).

You are right, I will wait for a guice release before releasing the new guicey. But, at least, now you can try a [snapshot](https://github.com/xvik/dropwizard-guicey#snapshots)

I think it's better to keep this issue open so everyone could track guice 5 upgrade status.

**Comment by xvik** [comment]
Guice released, but there might be a bugfix release soon due to a manifest typo (not important for us, but still). 
The new guicey will be released soon (should be next week). There will be no changes except the guice 5 (to simplify upgrade).

**Comment by gjvoosten** [comment]
Nice work, @xvik ! :+1:

**Comment by TIBCOeddie** [comment]
Came in looking for this; look forward to the new guicey version!

**Comment by xvik** [comment]
Will release today

**Comment by xvik** [comment]
[Released](http://xvik.github.io/dropwizard-guicey/5.3.0/about/release-notes/)
