### ISSUE TITLE
How to use guice beans 

### ISSUE THREAD

**Issue by wzhongyuan** [xvik/dropwizard-guicey#140]
seems if i added guice bundle in my application, i cannot use `DynamicFeature` correctly

https://github.com/mokies/ratelimitj/issues/48

**Comment by xvik** [comment]
It looks like jetty (9.4.33) regression appeared with dropwizard 2.0.15. To fix this just update to 2.0.16 or 2.0.17 (which brings fixed jetty).

For reference: `https://github.com/eclipse/jetty.project/issues/5555`

Also, this is not guicey:

```java
guiceBundle = GuiceBundle.<KrylovMasterConfiguration>newBuilder()
        .addModule(new ConfigModule())
        .addModule(new ResourceModule())
        .addModule(new CoreServiceModule())
        .addModule(new AuthModule())
        // .addModule(new CommonModule()) // Needed for workflow and workspace, do not remove
        //.addModule(new ZookeeperClientModule()) //Needed for workflow and workspace, do not remove
        .addModule(new DefaultServerModule())
        .addModule(new DefaultWorkspaceModule())
        .addModule(new ExtensionModule())
        .addModule(new RateLimitModule())
        //.enableAutoConfig(getClass().getPackage().getName())  // disable this to prevent accidental registration.
        .setConfigClass(KrylovMasterConfiguration.class)
        .build();
```

Most likely, you are using dropwizard-guice (or dropwizard-guicier) here

**Comment by wzhongyuan** [comment]
@xvik Thanks, is it same as https://github.com/xvik/dropwizard-guicey/issues/40 ?

**Comment by wzhongyuan** [comment]
@xvik  I am working on a legacy system, it may be not that easy to upgrade the version, is there any other solution ?
below is the version info

```shell
 <dropwizard.version>1.3.5</dropwizard.version>
    <dropwizard-guice.version>1.3.5.0</dropwizard-guice.version>
```

**Comment by xvik** [comment]
I was trying to say that you're using a different library [dropwizard-guice](https://github.com/HubSpot/dropwizard-guice) and not dropwizard-guicey (confusing names, I know). The library has been deprecated [in favor of dropwizard-guicier](https://github.com/HubSpot/dropwizard-guice#note), which is also seems to be abandoned now, but anyway it may fit your current needs.

Or you can [migrate to dropwizard-guicey](http://xvik.github.io/dropwizard-guicey/4.2.2/guide/dg-migration/) (version [4.2.2](http://xvik.github.io/dropwizard-guicey/4.2.2/getting-started/) will work for dropwizard 1.3).

The configuration above would change to:
```java
guiceBundle = GuiceBundle.builder()
        .modules(
                new ConfigModule(),
                new ResourceModule(),
                new CoreServiceModule(),
                new AuthModule(),
                //new CommonModule(), // Needed for workflow and workspace, do not remove
                //new ZookeeperClientModule(), //Needed for workflow and workspace, do not remove
                new DefaultServerModule(),
                new DefaultWorkspaceModule(),
                new ExtensionModule(),
                new RateLimitModule())
      //.enableAutoConfig(getClass().getPackage().getName())  // disable this to prevent accidental registration.
      .build();
```

But it would be better to enable auto-configuration so guicey could register extensions for you. This guicey version can't register them directly from guice declarations (feature available only in newer versions).
