### ISSUE TITLE
Injector creation time/ Application startup slow

### ISSUE THREAD

**Issue by sheldon-sminq** [xvik/dropwizard-guicey#15]
I enabled the statistics collection 

` GUICEY started in 2.414 min
    │   
    ├── [0.74%] CLASSPATH scanned in 1.073 s
    │   ├── scanned 806 classes
    │   └── recognized 42 classes (5.2% of scanned)
    │   
    ├── [0.015%] BUNDLES processed in 22.29 ms
    │   └── 2 processed
    │   
    ├── [99%] INJECTOR created in 2.396 min
    │   ├── installers prepared in 8.496 ms
    │   │   
    │   ├── extensions recognized in 30.37 ms
    │   │   ├── using 11 installers
    │   │   └── from 806 classes
    │   │   
    │   └── 42 extensions installed in 11.79 ms
    │   
    ├── [0.015%] HK bridged in 22.32 ms
    │   ├── using 2 jersey installers
    │   └── 39 jersey extensions installed in 12.88 ms
    │   
    └── [0.0062%] remaining 9 ms
`

Is this normal, Guicey takes over 2 min to setup everything. Or do i have some configuration issues?

**Comment by xvik** [comment]
injector creation takes all time: `[99%] INJECTOR created in 2.396 min`. As you can see below it, guicey time inside injector creation is tiny.

Was it the same time with guicey 3.2.0?

**Comment by sheldon-sminq** [comment]
It was quick in the previous version, but now when i try to downgrade i get the same performance. So not sure what packages changed.

Also 
`[0.74%] CLASSPATH scanned in 1.073 s │ ├── scanned 806 classes │ └── recognized 42 classes (5.2% of scanned) `

Is interesting, i will try out manual instead of auto to see if that helps improve

**Comment by xvik** [comment]
By the way, don't be scared of large classpath scan time: the largest part of this time is class loading. Most likely you will use all these classes and they will still be loaded (time spent on classpath scan will move to some other place). 
You can try to experiment and look if overall startup time (printed by dropwizard) changes.

**Comment by xvik** [comment]
For history: issue was caused by [slow quartz initialization](https://github.com/xvik/dropwizard-guicey/issues/14#issuecomment-237320230)
