### ISSUE TITLE
GuiceyAppRule should apply configuration overrides in before() phase

### ISSUE THREAD

**Issue by bwehrle** [xvik/dropwizard-guicey#151]
Hi,
I noticed a problem when building a test for a microservice.  The test uses a Junit RuleChain
```java
 public static final GuiceyAppRule<MicroServiceConfiguration> appContextRule = new GuiceyAppRule<>(
      TestMicroServiceApplication.class,
      "src/integration/resources/integration-test-config.yml",
      ClientTestConfiguration.clientConfigOverrides(()->wireMockRule.getOptions().portNumber())
  );

  @ClassRule
  public static final RuleChain chain = RuleChain
      .outerRule(wireMockRule)
      .around(appContextRule));
```

What I expect to happen is that the ConfigurationOverride is applied after the outer rule (wireMockRule) has be started and executed it's before().  This is not the case.

I propose a fix that moves the application of the ConfigurationOverrides to the before() method and not in the constructor.

```java
  private List<ConfigOverride> configOverrideList;

  public GuiceyAppRule(final Class<? extends Application<C>> applicationClass,
      @Nullable final String configPath,
      final ConfigOverride... configOverrides) {
    this.applicationClass = applicationClass;
    this.configPath = configPath;
    this.configOverrideList = Arrays.asList(configOverrides);
  }
  ...
 @Override
  protected void before() throws Throwable {
    # configOverrideList : the configuration overrides provided in the constructor method
    for (ConfigOverride configOverride : configOverrideList) {
      configOverride.addToSystemProperties();
    }
    startIfRequired();
  }
```
Will provide a PR.

**Comment by xvik** [comment]
Completely agree. 

GuiceyAppRule was based on DropwizardAppRule (copying its behavior) and at that time dropwizard rule was initialized in the constructor. Now it initializes in `before()` so the guicey rule should do the same.

**Comment by bwehrle** [comment]
Thanks for resolving this issue for this class.  I had made the same change
yesterday.  However, after making the change and validating the test
result, I saw no break in tests.  Therefore, I think there is still a
missing test here for this functionality.  Happy to write a test for this.

When looking into the Junit5 implementation, I could not see a way to do
this same use case due to the way configuration overrides are defined
(Strings, not ConfigurationOverrides).  If this is possible, it might be
good to add some note in the documentation about how this works.

**Comment by xvik** [comment]
Yes, I was thinking about junit 5 too. If everything goes well then I'll add it today (just started looking at it). Ofc. it would work only for the `@RegisterExtension` registration type (with a builder).

Overall I want to release a new version with guice 5 today (max tomorrow). 

I was waiting for your PR but finally assumed that you treat my comment as "I will do it". Test PR would also be wonderful.

**Comment by xvik** [comment]
Junit 5 support also added.

```java
    @RegisterExtension
    @Order(1)
    static FooExtension ext = new FooExtension();

    @RegisterExtension
    @Order(2)
    static TestGuiceyAppExtension app = TestGuiceyAppExtension.forApp(AutoScanApplication.class)
            .config("src/test/resources/ru/vyarus/dropwizard/guice/config.yml")
            .configOverrides("foo: 1")
            .configOverride("bar", () -> ext.getValue())
            .configOverrides(new ConfigOverrideValue("baa", () -> "44"))
            .create();
```

But there is a catch: it accepts only `ConfigOverride` objects implementing custom guicey interface `ConfigurablePrefix`. 
In order to support parallel tests, guicey generates overriding properties prefix per test (because all config overrides are stored as system properties). This interface allows me to set this prefix into any custom `ConfigOverride` objects.

`ConfigOverrideValue` used above is also not dropwizard's one, but a custom implementation (essentially the same).

Overall, I think this complication wouldn't cause too many problems (but should save some nerves).

**Comment by bwehrle** [comment]
Awesome.  I wanted to move the tests in question to JUnit5, so this makes
that possible.
I don't see any reason why this above constraints would be a problem, since
developers are not usually subclassing ConfigOveride (it is not something
that new behaviour would be added to)- since the functionality already
allows for dynamic behaviour via the lambda param in the constructor.

The inconvenience, almost none, is well worth the gains.  Thanks for adding
this!
