### ISSUE TITLE
Could not get Guice Injector now

### ISSUE THREAD

**Issue by ange1ann** [xvik/dropwizard-guicey#16]
public class ManagedGovernator implements Managed {

    private LifecycleManager manager;

    public ManagedGovernator() {
        manager = GuiceBundle.getInjector().getInstance(LifecycleManager.class);
    }

   GuiceBundle.getInjector() we could not use this method now.
   How to fix it?

  The code is from : https://github.com/xvik/dropwizard-guicey/wiki/Governator-Integration

**Comment by xvik** [comment]
Hi,

Injector is not static anymore to let you write concurrent tests. 

You can simply let guice inject LifecycleManager for you:

```java
public class ManagedGovernator implements Managed {

   @Inject
    private LifecycleManager manager;

    @Override
    public void start() throws Exception {
        manager.start();
    }

    @Override
    public void stop() throws Exception {
        manager.close();
    }
}
```

If you use auto scan (like in example in wiki):

```java
bootstrap.addBundle(GuiceBundle.<TestConfiguration> builder()
            .injectorFactory(new GovernatorInjectorFactory())
            .enableAutoConfig("package.to.scan")
            .modules(new MyModule())
            .build()
    );
```

and your ManagedGovernator is in scanned package then guicey will find it and register automatically.

Note that in wiki example managed was registered manually and so guice injection for LifecycleManager was impossible.
I will update wiki page too.

**Comment by ange1ann** [comment]
Thanks for your help!
