### ISSUE TITLE
@Inject is always null

### ISSUE THREAD

**Issue by sysmat** [xvik/dropwizard-guicey#17]
@Inject is always null

I'm new with dropwizard-guicey and it looks like a very great project.

I'm using dropwizard:1.0.0 and dropwizard-guicey:4.0.0

I'm trying to figure it out why @Inject class is always null in log is nothing special to see.

Here is a  spinets:

`
public class GuiceModule extends DropwizardAwareModule<AppConfiguration> {
   private Client client;

@Override
protected void configure() {        
        client = ClientBuilder.newBuilder().build();	
}

@Provides
@Singleton
public Client prepareClient() {
        LOG.info("client={}", client);
        return this.client;
}

public class ServiceApplication extends Application<AppConfiguration> {

@Override
public void initialize(final Bootstrap<AppConfiguration> bootstrap) {
        
        bootstrap.addBundle(GuiceBundle.<AppConfiguration>builder()
			.enableAutoConfig("arnes.dropwizard")
			.modules(new GuiceModule())                        
			.build()
		);
        }
}

public class MyAuthenticator implements Authenticator<BasicCredentials, UserAuth> {

@Inject	
private Client client;

@Override
public Optional<UserAuth> authenticate(BasicCredentials credentials) throws AuthenticationException{
        LOG.info("client={}", client);
}

}
`

And client is always null, si what I'm doing wrong?

Regards, Tomaz

**Comment by xvik** [comment]
Hi,

Unfortunately, you did not show how you use `MyAuthenticator`. If you inject it somewhere (some guice managed class) or retrieve instance directly from injector (injector.getInstance()) then `client` should be injected. Almost sure that MyAuthenticator is instantiated directly somewhere by mistake.

I can suggest to use constructor injection: this way it will be impossible to construct not completely initialized bean (by mistake):

```java
@Inject
public MyAuthenticator (Client client) {
    this.client = client
}
```

Can't tell more without additional info.

As a side note, prefer instance bindings for such cases, they look much more elegant:
```java
@Override
protected void configure() {
    bind(Client.class).toInstance(ClientBuilder.newBuilder().build());
}
```

**Comment by sysmat** [comment]
Hi,

thx for your replay, I have only default constructor, when I  set authenticator to jersey:

`.setAuthenticator(new MyAuthenticator())`

and is always null.

And thx for instance bindings tip, but for me is not vary logical, because you bind for every javax.ws.rs.client.Client and not some specific .

Let see case if I want to provide two different DBI with different configuration, so in that case I still need two  methods with @Provides annotation.

Regards, Tomaz

**Comment by xvik** [comment]
Hi,

If you do `new MyAuthenticator()` then guice will not manage instance and so will not inject client inside MyAuthenticator. You can use either direct injector access to obtain instance (`InjectorLookup.getInjector(this).get().getInstance(MyAuthenticator.class)`) or (better) restructure your code to let guice provide instances for you ( see, for example, [auth customization](https://github.com/xvik/dropwizard-guicey/wiki/Authentication-integration) in such way)

You can always qualify direct binding, like 

```java
bind(Client.class).annotatedWith(Names.named("one")).toInstance(ClientBuilder.newBuilder());
```

But of course, it's a matter of taste to use provider or direct binding.

**Comment by sysmat** [comment]
Hi,

thx for your answers, currently I didn't  restructured my code but I was trying with   InjectorLookup and for the client it look ok, but now I'm trying to use DBI:

`
private DBI jdbiMyDB;     

    @Override
    protected void configure() {
        DBIFactory factory = new DBIFactory();
        this.jdbiMyDB = factory.build(environment(), configuration().dataSourceFactory, "mysql2"); 
        LOG.info("jdbiMyDB={}", jdbiMyDB);
        bind(Client.class).toInstance(ClientBuilder.newBuilder().build());   // OK - Instance
        bind(UserAuthDao.class).toInstance(jdbiMyDB.onDemand(UserAuthDao.class));  // NOT OK - not instance
   }
`

And in MyAuthenticator:
`
@Inject  private UserAuthDao userAuth; // null

@Inject private Client client; // not null
`

Regards, Tomaz

**Comment by sysmat** [comment]
Hi,
sorry to bother you it's working, so the key is not to use constructor and using InjectorLookup.

Regards, Tomaz

**Comment by xvik** [comment]
Glad to hear it's working)
If you have other questions feel free to ask me. I did a special [google group](https://groups.google.com/forum/#!forum/dropwizard-guicey) for it, but issues are also ok (if it's more comfortable for you).
