### ISSUE TITLE
Guice 5.1.0 Support

### ISSUE THREAD

**Issue by ChangsoonKim** [xvik/dropwizard-guicey#213]
Hi xvik, 

Our applicatoin will be use Java 17.

Guice 5.1.0 was released and this version [officially support Java 17](https://github.com/google/guice/wiki/Guice510).

I checked that [supporting Guice 5.1.0 PR](https://github.com/xvik/dropwizard-guicey/commit/8a7d1ab1695e0ce0cd67c02a944c0d4e97da58e4) was merged. 

When will the supporting Guice 5.1.0 version be released?

Thanks.

**Comment by xvik** [comment]
Hi!
I'll do it today or tomorrow. It would be a 5.4.2 release with only changed dropwizard and guice versions.

**Comment by ChangsoonKim** [comment]
Thank you so much xvik!

**Comment by xvik** [comment]
[released 5.4.2](https://github.com/xvik/dropwizard-guicey/releases/tag/5.4.2)

**Comment by ChangsoonKim** [comment]
we was changed dw-guicey version 5.0.1 to 5.1.0.

Thank you so much.
