### ISSUE TITLE
Rebuild against Dropwizard 1.0.4

### ISSUE THREAD

**Issue by reneploetz** [xvik/dropwizard-guicey#24]
When trying to use 4.0.0 in Dropwizard 1.0.4 the GuiceBridge fails with this error:
```java
! java.lang.NoSuchMethodError: org.glassfish.hk2.utilities.BuilderHelper.getRank(Ljava/lang/Class;)I
! at org.jvnet.hk2.internal.Utilities.createAutoDescriptor(Utilities.java:723)
! at org.jvnet.hk2.internal.DynamicConfigurationImpl.addActiveDescriptor(DynamicConfigurationImpl.java:196)
! at org.jvnet.hk2.guice.bridge.internal.GuiceBridgeImpl.initializeGuiceBridge(GuiceBridgeImpl.java:82)
! at ru.vyarus.dropwizard.guice.module.jersey.GuiceFeature.configure(GuiceFeature.java:62)
```

Overriding org.glassfish.hk2:guice-bridge to 2.5.0-b05 (the version used by Dropwizard) it will fail with:
```java
Exception in thread "main" java.lang.NoSuchMethodError: com.google.inject.binder.AnnotatedBindingBuilder.toProvider(Ljavax/inject/Provider;)Lcom/google/inject/binder/ScopedBindingBuilder;
	at ru.vyarus.dropwizard.guice.module.installer.util.JerseyBinding.bindJerseyComponent(JerseyBinding.java:138)
	at ru.vyarus.dropwizard.guice.module.jersey.hk2.GuiceBindingsModule.jerseyToGuice(GuiceBindingsModule.java:75)
	at ru.vyarus.dropwizard.guice.module.jersey.hk2.GuiceBindingsModule.configure(GuiceBindingsModule.java:53)
```

Note that just recompiling against org.glassfish.hk2:guice-bridge:2.5.0-b05 / Dropwizard 1.0.4 does not cause any compile errors, but will probably break backwards compatibility :/

Can you provide an update nevertheless?

**Comment by sheldon-sminq** [comment]
<dependency>
    <groupId>org.glassfish.hk2</groupId>
    <artifactId>guice-bridge</artifactId>
    <version>2.5.0-b05</version>
</dependency>

Add this dependency, Dropwizard is using this version but Guicey is using an older version. Till thats updated adding this dependency works.

**Comment by xvik** [comment]
Thank you! I'll do bugfix release today.

**Comment by xvik** [comment]
4.0.1 [released](https://github.com/xvik/dropwizard-guicey/releases/tag/4.0.1) for dropwizard 1.0.5

**Comment by reneploetz** [comment]
Thank you!
