### ISSUE TITLE
HK2 managed resources are forced into singleton scope

### ISSUE THREAD

**Issue by chr1st1anh** [xvik/dropwizard-guicey#25]
In the ResourceInstaller the HK2 managed resources are forced into the singleton scope, this is the code:
``` 
 @Override
  public <T> void install(final Binder binder, final Class<? extends T> type, final boolean lazy) {
    if (!isHK2Managed(type) && !lazy) {
      // force singleton
      binder.bind(type).in(Singleton.class);
    }
  }
```

Whenever we inject some Session or just differently scoped beans into a Resource they will be kept as singletons. Is there a good reason for this? In our case a simple workarounds like overriding the classes that are involved and binding the Resources without the Singleton scope seems to solve the problem.

**Comment by xvik** [comment]
I don't see any good reason to not use singleton scope for resources: it's insane to create them per request. 
You can always use [Provider<> binding](https://github.com/xvik/dropwizard-guicey#request-scoped-beans) to access scoped beans (e.g. to access request itself). 

Dropwizard intended to be used for stateless rest services, so it's logical to keep all (or almost all) beans in the singleton scope. Of course, no one stops you from using state (and enable sessions support).

One of the benefits of installers approach is flexibility: if current resource installer does not match your needs, you can simply replace it with your own version (disable core installer and register your custom version).

I may not completely understand your question, so please tell me if I miss the point.

**Comment by chr1st1anh** [comment]
You did not miss the point and thanks for the Answer! The application stores a lot of state and is very low throughput and for this reason the extra object creation at the resource level never bothered. Currently I think the `Provider<>` solution will work and will push the application to use more best practices.
