### ISSUE TITLE
Add jerseyToGuice binding for ResourceInfo in GuiceBindingsModule

### ISSUE THREAD

**Issue by tfeak** [xvik/dropwizard-guicey#26]
In the GuiceBindingsModule.configure() method you bridge existing Jersey bindings to Guice bindings. I've found this verify helpful for accessing things like the HttpServletRequest in numerous places. However, I've found that the ResourceInfo isn't bound this way. It seems like it could also be made available the same way, though I haven't verified that.

In my particular use case, I have a Filter that I inject via Guice. The Filter is bound as a singleton. The filter uses both the HttpServletRequest and the ResourceInfo. I can mark the member variables in the Filter with @Context and this works fine. However, if I remove that annotation and move them into the constructor (with Provider<>s for them), only the HttpServletRequest binding can be found. The ResourceInfo binding isn't.

**Comment by xvik** [comment]
Good idea, thank you. I will add it in the next release (next year).

For now, you can enable binding manually inside your guice module:

```java
public class YourGuiceModule extends AbstractModule {
    protected void configure() {
        JerseyBinding.bindJerseyComponent(binder(), new InjectorProvider(appInstance), ResourceInfo.class);
    }
}
```
where appInstance is an application instance.

**Comment by tfeak** [comment]
Thank you for the rapid response and workaround!

**Comment by xvik** [comment]
[Released](https://github.com/xvik/dropwizard-guicey/releases/tag/4.1.0)
