### ISSUE TITLE
Reuse application between test classes

### ISSUE THREAD

**Issue by anton-kapelyushok** [xvik/dropwizard-guicey#269]
From documentation of @TestDropwizardApp: 
> Application started before all tests in annotated class and stopped after them.

Is it possible to reuse application between test classes? 

Some usecases which can be improved significantly:
- docker compose startup before tests
- DB initialization before tests

**Comment by xvik** [comment]
>Is it possible to reuse application between test classes?

You can only use [nested tests](http://xvik.github.io/dropwizard-guicey/latest/guide/test/junit5/#junit-nested-classes): in this case application declared on root class would be re-used in all nested tests.

There is no other way in junit to group tests (for extension) and so I can't do anything "in general". In theory, it is possible to support "before all tests" case [using root state](https://stackoverflow.com/questions/43282798/in-junit-5-how-to-run-code-before-all-tests), but not sure it would be a good idea.

What usually works best is creating your own custom junit extension: there are [supporting classes for both full app and lightweigh context cases](http://xvik.github.io/dropwizard-guicey/latest/guide/test/general/#advanced-usage) which you can use to start application in your extension (with just one line).

I'm open for discussion if you have concrete suggestion. Or, if you describe your case in details, we can think about it (based on concrete situation).

> Some usecases which can be improved significantly:

> docker compose startup before tests
> DB initialization before tests

Usually, such things implemented as junit extensions so there should be no problem combining it with guicey extension (run db init before app start). To configure application using other extensions data, there is a [deferred configuration](http://xvik.github.io/dropwizard-guicey/latest/guide/test/junit5/#deferred-configuration) (or, if required values available in storage, these values [could be used directly](http://xvik.github.io/dropwizard-guicey/latest/guide/test/junit5/#configuration-from-3rd-party-extensions)). 

In case of completely manual db initialization, special [setup callback](http://xvik.github.io/dropwizard-guicey/latest/guide/test/junit5/#test-environment-setup) might be used. 

I would be able to suggest something more concrete if I knew the exact use-case (and the actual problems).

**Comment by anton-kapelyushok** [comment]
I am coming from a spring world where application context is cached between the tests and thought something similar is implemented for dropwizard (apparently it is not)
https://docs.spring.io/spring-framework/docs/current/reference/html/testing.html#testing-ctx-management
I think it is still possible to implement it, you can use TestDropwizardApp instance as a cache key or whatever.

In spring I am used to put docker container creation and db migration in application initialization stage, which works great when context is created once and reused in each test class. 
I tried to make it the same way in dropwizard app, and stumbled upon the subject problem.

I will try to move container creation and db initialization to the rule with root state, as you suggested. 
Thank you!

**Comment by xvik** [comment]
Good point about spring - I forgot it works like this. I will read the details of how it works in spring and try to introduce application caching in tests.

For now, I think the simplest solution would be to rely on extension declaration in base class: 

```java
@TestGuiceyApp(value = MyApp.class, reuseContext = true)
public abstract class BaseTest { ... }

public class Test1 extends BaseTest { ... }

public class Test2 extends BaseTest { ... }
```

If annotation in base class (or extension, declared in field with `@RegisterExtension`) explicitly enables reuse (not enabled by default for backwards compatibility) then all derived tests would use the same context. Looks logical and should be flexible enough.
