### ISSUE TITLE
PolymorphicAuthDynamicFeature support

### ISSUE THREAD

**Issue by sheldon-sminq** [xvik/dropwizard-guicey#27]
Can we use PolymorphicAuthDynamicFeature the same way as AuthDynamicFeature?

```
public class MultiAuthFeature extends PolymorphicAuthDynamicFeature {
  super(ImmutableMap.of(
        BasicPrincipal.class, basicFilter,
        OAuthPrincipal.class, oauthFilter)));
final AbstractBinder binder = new PolymorphicAuthValueFactoryProvider.Binder<>(
    ImmutableSet.of(BasicPrincipal.class, OAuthPrincipal.class));
environment.jersey().register(binder);
}
```

**Comment by pandaadb** [comment]
Hi,

I think you just do? This is not really a guice issue, so I would recommend looking into the DW docs: 

http://www.dropwizard.io/1.0.6/docs/manual/auth.html

In terms of how to do this in Guice, you could e.g. use multibindings to register multiple authFilters and inject them into your ChainedAuthFilter. For that I think you will likely to either wrap the filter into some sort of manager-class (something that can be injected + can create your auth filter), or use the AuthFilter directly by extending it and having it injected.  

Alternatively, create it manually in your module and bind the instance so you can use it in a guice context. 

Does that help?

**Comment by sheldon-sminq** [comment]
This is the class i have implemented

```
public class MultiAuthFeature extends PolymorphicAuthDynamicFeature {

    @Inject
    public MultiAuthFeature(KeyAuthenticator keyAuthenticator,
                            BasicAuthenticator basicAuthenticator,
                            JwtAuthenticator jwtAuthenticator,
                            JwtConsumer jwtConsumer,
                            Environment environment) {

        super(ImmutableMap.of(ApiAccess.class,new ChainedAuthFilter(Lists.newArrayList(
                new BasicCredentialAuthFilter.Builder<ApiAccess>()
                        .setPrefix("Basic")
                        .setAuthenticator(new CachingAuthenticator<>(
                                new MetricRegistry(), keyAuthenticator, CacheBuilderSpec.parse("maximumSize=10000, expireAfterAccess=10m")))
                        .buildAuthFilter(),
                new JwtAuthFilter.Builder<ApiAccess>()
                        .setJwtConsumer(jwtConsumer)
                        .setRealm("realm")
                        .setPrefix("Bearer")
                        .setAuthenticator(new CachingAuthenticator<>(
                                new MetricRegistry(), jwtAuthenticator, CacheBuilderSpec.parse("maximumSize=10000, expireAfterAccess=10m")))
                        //                        .setAuthorizer(apiAuthorizer)
                        .buildAuthFilter())),KeyAccess.class,new BasicCredentialAuthFilter.Builder<KeyAccess>()
                .setPrefix("Basic")
                .setAuthenticator(new CachingAuthenticator<>(
                        new MetricRegistry(), basicAuthenticator, CacheBuilderSpec.parse("maximumSize=10000, expireAfterAccess=10m")))
                .buildAuthFilter()));
        final AbstractBinder binder = new PolymorphicAuthValueFactoryProvider.Binder<>(
                ImmutableSet.of(ApiAccess.class, KeyAccess.class));
        environment.jersey().register(binder);
        //        environment.jersey().register(RolesAllowedDynamicFeature.class);

    }
}
```

Using a PolymorphicAuthDynamicFeature to support multiple authentication schemes for different resources.

**Comment by sheldon-sminq** [comment]
So will the manual install work?

```
public class AuthBundle implements GuiceyBundle {
    @Override
    public void initialize(GuiceyBootstrap bootstrap) {
        bootstrap.extensions(MultiAuthFeature.class);
    }
}
```

**Comment by pandaadb** [comment]
That looks about right, you should now have the desired behaviour (using the auth filters one at a time to see if one pass). Your answer does not contain a question, so I am not sure if you need to know something else? 

In terms of guicey, I Think if you wanted this to be installed, you would need to annotate your MultiAuthFeature class with @Provider and enable the extensions in guicey. That way it will discover them on startup and register them with jersey automatically for you.

**Comment by sheldon-sminq** [comment]
Since the doc only had an example of injecting AuthDynamicFeature i just wanted to confirm if PolymorphicAuthDynamicFeature would work exactly the same way. Thanks for the info.

**Comment by pandaadb** [comment]
Yes, you are right (I forgot there was an example).

Basically, what the example does is take advantage of the injection and the installers that guices ships with.

By extending the base class, you can add the Inject annotation to use it for creating the class by guice and injecting the filters into it. 

By adding the Provider annotation you tell the jersey installer to bind that specific class into the jersey eco-system. After that, everything happens on its own (e.g. if you have an auth annotation on your resource, it will install your dynamic feature)

**Comment by xvik** [comment]
@pandaadb thank you for help!

I'm working on documentation site right now which, I hope, would be much more informative and simplify the search for answers. 

As I can see, the question is perfectly answered. @sheldon-sminq please reopen it if some questions remain.
