### ISSUE TITLE
Superfluous Home Page in Wiki

### ISSUE THREAD

**Issue by segfly** [xvik/dropwizard-guicey#3]
When I created the wiki page refereed to in xvik/dropwizard-guicey/issues/1 GitHub automatically created a home page in the Wiki. I tried to delete it, but I received a an error. It has a default message at the moment and I was unsure if it shoudl be cleaned up.

According to http://stackoverflow.com/a/13112154 it can be deleted via git. Or, maybe some content should be put on the home page?

**Comment by xvik** [comment]
Let it be a TOC now.
Suppose there will be more pages later and then home page would be relevant, otherwise we will remove it sometime
