### ISSUE TITLE
Guicey-eventbus

### ISSUE THREAD

**Issue by sheldon-sminq** [xvik/dropwizard-guicey#33]
We have a question related to the Guicey event bus, we have a bunch of listeners but do not bind those listeners manually.

Is there a way to automatically inject these listeners that have the @Subscribe annotation, these listeners have other classes injected in their constructers. 

so we cannot do something like
bind(Listener.class).toInstance(new Listener());

**Comment by xvik** [comment]
Eventbus integration [use guice type listener](http://xvik.github.io/dropwizard-guicey/4.0.1/extras/eventbus/#listeners-recognition) for detection. This means that it checks all registered guice beans.

So all you have to do is register your listener beans. There may be different ways:
1. Bind all listener beans manually: `bind(Listener.class).in(Singleton.class)` (or make it singleton with annotation so guice will instantiate it on injector creation).
2. Use [@EagerSingleton](http://xvik.github.io/dropwizard-guicey/4.0.1/installers/eager/) extension: guicey will bind such classes as singletons automatically.
3. Write your own installer to detect and bind listeners (the same as eager singleton, but with your marker)

For me, option 2 is the simplest, but I don't know your exact situation.

**Comment by sheldon-sminq** [comment]
We went the installer way which works thanks.
