### ISSUE TITLE
Guice injection doesn't seem to work in custom exception mappers with guicey

### ISSUE THREAD

**Issue by imochurad** [xvik/dropwizard-guicey#34]
I have a project, where I disable default exception mappers and override them with custom implementations. Now, in one of those exception mappers I'd like to inject one of the objects I have configured in my module. Doesn't seem to work. As the mapper object is being created by the HK2 injector.

Is there a workaround to this issue? Config?

**Comment by xvik** [comment]
You can let guicey [install your exception mappers](http://xvik.github.io/dropwizard-guicey/4.1.0/installers/jersey-ext/#exceptionmapper). In this case, exception mappers would be created by guice and so all injections would work.

If you prefer to let hk to manage your mappers, then [enable hk-guice-bridge](http://xvik.github.io/dropwizard-guicey/4.1.0/guide/configuration/#hk-bridge) so hk could inject guice beans.

And be sure that you are not registering exception mapper instances directly.

**Comment by imochurad** [comment]
Thanks, I have removed explicit mappers registration and it started to work as a charm.
