### ISSUE TITLE
Dropwizard v2.1.9 for Guicey Branch dw-2.1

### ISSUE THREAD

**Issue by JKomoroski** [xvik/dropwizard-guicey#347]
Dropwizard v2.1.9 is out. There is a commit to update Guicey to 2.1.9 but the [build failed](https://github.com/xvik/dropwizard-guicey/commits/dw-2.1). Is there something you need help with testing? Following up my comment on the Gitter channel.

**Comment by xvik** [comment]
It's not failed, just codecov reported a bit reduced coverage. The problem with 2.1.9 was leaked jdbi3 version (for gradle build) not compatible with java 8. I fixed that, but it would require manual fix in all gradle projects too.

I was just waiting if dropwizard would release a new version (like they did with 2.1.9 soon after 2.1.8), but seems they are not going to do it.
I will release new versions soon (most likely, this weekend)

**Comment by JKomoroski** [comment]
Sounds good. I'll wait for that. Thank you.

**Comment by xvik** [comment]
5.9.3 [released](https://github.com/xvik/dropwizard-guicey/releases/tag/5.9.3)

Versions for dropwizard 3 and 4 are suspended for now - I assume there would be new releases soon due to https://www.github.com/dropwizard/dropwizard/issues/7830
