### ISSUE TITLE
Event Name Typo

### ISSUE THREAD

**Issue by greylurk** [xvik/dropwizard-guicey#387]
https://github.com/xvik/dropwizard-guicey/blob/593d1f235aa23a238e303d8006ca092027c7c7a6/dropwizard-guicey/src/main/java/ru/vyarus/dropwizard/guice/module/lifecycle/event/jersey/ApplicationShotdownEvent.java#L18

should be `ApplicationShutdownEvent`

**Comment by xvik** [comment]
Thank you! I'll fix

**Comment by xvik** [comment]
This would be a breaking change for everyone using this event directly. But I hope there are just a few custom usages, so upcoming version would still be a hotfix version.
