### ISSUE TITLE
Custom @Context in dropwizard/guicey

### ISSUE THREAD

**Issue by craigching** [xvik/dropwizard-guicey#39]
What is the right way to create a custom @Context object?  I am migrating from RestEasy to Dropwizard/Guicey.  In RestEasy I used:

        ResteasyProviderFactory.pushContext(TenantId.class, tid);

from within a ContainerRequestFilter and my resources could then use it like:

        @GET
        public String getFoo(@Context TenantId tenantId) { ... }

I can't quite figure out how to do the same in dw/guicey and help is appreciated!

**Comment by xvik** [comment]
You need to declare `Factory<TenantId>`, like this:

```java
@javax.ws.rs.ext.Provider
public class TenantIdParamFactory implements Factory<TenantId> {

    @Inject
    private Provider<HttpServletRequest> requestProvider;

    @Override
    public TenantId provide() {
        // as an example, resolving tenant by request parameter
        final String tenant = requestProvider.get().getParameter("tenant");
        return new TenantId(tenant == null ? "unknown" : tenant);
    }

    @Override
    public void dispose(TenantId instance) {
    }
}
```

Factory will be installed by [jersey extensions installer](http://xvik.github.io/dropwizard-guicey/4.1.0/installers/jersey-ext/#factory) and context parameter mapping (`getFoo(@Context TenantId tenantId)` will work. 

You can use [jersey request objects](http://xvik.github.io/dropwizard-guicey/4.1.0/guide/bindings/#jersey-specific-bindings) the same way as a request in the example above.

**Comment by craigching** [comment]
Wow, so simple and I've tried everything under then sun! ;)  I'll give this a try this weekend and post back about my experience.  Thanks so much for the quick reply!

**Comment by craigching** [comment]
yep, this definitely works in a simple test and also in my real code.  Awesome, thanks much!
