### ISSUE TITLE
Support for Java 21

### ISSUE THREAD

**Issue by thiagohora** [xvik/dropwizard-guicey#393]
I noticed that in the documentation, it's stated that the module is compatible with Java 11 - 17. Is there any major issue to support the 21 version? Are there any plans to do so? 

I tried in a very simple project, and it worked, but I want to know if there is any major issue.

**Comment by xvik** [comment]
Yes, it works with java 21. Guicey itself did not put any limits (except asm version used by guice) for java version, so any java supported by dropwizard should work.

Java 11 - 17, mentioned in docks, just indicate that I test it on CI with 11 and 17. Recently, added java 21 on CI too, but did not updated the doc yet.
