### ISSUE TITLE
Guice injection doesn't seem to work in custom filters that extend ContainerRequestFilter

### ISSUE THREAD

**Issue by imochurad** [xvik/dropwizard-guicey#40]
Actually, the topic might be a little bit misleading. Guice injection works fine until I try to use Filters which are dynamically bound to resource methods using `DynamicFeature`.

Then I get: 

```Caused by: java.lang.NoSuchMethodException: The class LineSignatureValidationFilter has no constructor marked @Inject and no zero argument constructor
at org.jvnet.hk2.internal.Utilities.findProducerConstructor(Utilities.java:1279)
at org.jvnet.hk2.internal.DefaultClassAnalyzer.getConstructor(DefaultClassAnalyzer.java:83)
at org.jvnet.hk2.internal.Utilities.getConstructor(Utilities.java:178)
```

How do I force my filter to use Guice injector in this case?

**Comment by xvik** [comment]
Could you please show an example?

**Comment by imochurad** [comment]
```
@Provider
public class MySignatureValidationFeature implements DynamicFeature {
	@Override
	public void configure(ResourceInfo resourceInfo, FeatureContext context) {
		if (resourceInfo.getResourceMethod().getAnnotation(MySignatureValidation.class) != null) {
			context.register(MySignatureValidationFilter.class);
		}
	}
}
```

```
public class MySignatureValidationFilter implements ContainerRequestFilter {

	private final SecretRetriever secretRetriever;

	@Inject
	public MySignatureValidationFilter(SecretRetriever secretRetriever) {
                   this.secretRetriever = secretRetriever;
	}

	@Override
	public void filter(ContainerRequestContext requestContext) throws IOException {
        // implementation
       }
```

```
@Target({ElementType.METHOD})
@Retention(RetentionPolicy.RUNTIME)
public @interface MySignatureValidation {

}
```

```
public class MyResource  {

	@POST
	@Path("/myresource")
	@MySignatureValidation
	public Response post(final String payload) {
		// implementation
	}

}
```

**Comment by imochurad** [comment]
I want my filter to be triggered only on those resource methods that are annotated with my custom annotation. All works fine, except Jersey doesn't know how to create object of type `MySignatureValidationFilter `.

**Comment by xvik** [comment]
You have 2 options: either register filter by instance (guice managed instance) or enable guice bridge (so hk could see guice beans).

For the first option you need to use guice-managed filter instance:
```java
@Provider
public class MySignatureValidationFeature implements DynamicFeature {
        @Inject MySignatureValidationFilter filter;
        
	@Override
	public void configure(ResourceInfo resourceInfo, FeatureContext context) {
		if (resourceInfo.getResourceMethod().getAnnotation(MySignatureValidation.class) != null) {
			context.register(filter);
		}
	}
}
```
Note: I assume dynamic feature [is installed by guicey](http://xvik.github.io/dropwizard-guicey/4.1.0/installers/jersey-ext/#dynamicfeature)

For the second option, you need to [add bridge dependency and activate bridge option](http://xvik.github.io/dropwizard-guicey/4.1.0/guide/configuration/#hk-bridge). No other code changes required.

I would prefer the first way, as it does not require additional dependency which you will have to maintain later (to be compatible with the dropwizard version).

**Comment by imochurad** [comment]
Thanks, it works. The first option is the one I've selected.
