### ISSUE TITLE
@HK2Managed should be in an api module instead?

### ISSUE THREAD

**Issue by jontejj** [xvik/dropwizard-guicey#41]
As it's now (we used jersey2-guice before), we have some @javax.ws.rs.ext.Provider filters that can be used both on the client side by cxf or other javax.ws.rs compatible clients. But with dropwizard-guicey it becomes tricky as they depend on @Context being injected. This means that they should use either @HK2Managed or @Inject right? The problem with that is that @HK2Managed is in the main module of dropwizard-guicey which makes our api clients depend on dropwizard, guice etc.

I think it would be better to have a separate module for api's that can be at least not so intrusive on the classpath for api users? To minimize classpath problems for the api users I mean.

**Comment by jontejj** [comment]
btw, thanks for your awesome work on this project! Truly amazing work!

**Comment by xvik** [comment]
Yes, you either have to replace @Context usage with providers or use @HK2Managed to delegate management to hk. 

But in your case, it would be simpler to replace installer to always use hk managed beans. For example, resource installer could be changed like this:

```java
public class HkResourceInstaller extends ResourceInstaller {
    @Override
    public <T> void install(final Binder binder, final Class<? extends T> type, final boolean lazy) {
          // nothing
    }
    @Override
    public void install(final AbstractBinder binder, final Injector injector, final Class<Object> type) {
        // nothing
    }
}
```
This installer will recognize resources as before but will only put resource type into the dropwizard environment (so hk will manage it).

Replace default installer:

```java
GuiceBundle.builder()
    .disableInstallers(ResourceInstaller.class)
    // registratrion is not required if classpath scan is enabled and your custom installer would be in the scanned package
    .installers(HkResourceInstaller.class)
```

And you will need to [enable hk bridge](http://xvik.github.io/dropwizard-guicey/4.1.0/guide/configuration/#hk-bridge) so you can use (inject) guice services inside hk resources.

The same way you can replace JerseyProviderInstaller (your question was mostly about it) adapting it to your needs.

This way you will solve api-jar problem (you simply don't need guicey dependency anymore). 
For now, I don't plan to extract annotations to api jar. I understand why you suggest that and can even agree with the motivation, but don't see enough reasons to do it now.


It's not the first time when people asking about hk managed resources, so I think it would make sense to introduce a new option for switching jersey related installers from guice to hk mode (e.g. `.option(GuiceyOptions.HK_MODE, true)`) to avoid replacing the default installers.

**Comment by jontejj** [comment]
The installers are quite flexible, that's true. But @hk2managed kind of loses it's value for other internal providers then right?

We managed to move those filters into our core as they weren't really useful for the client anyway. I still think having an api/impl approach would be more bulletproof though.

I understand that you don't want to do this yet though, so I'm closing this!
