### ISSUE TITLE
Release a  new version

### ISSUE THREAD

**Issue by ganeshs** [xvik/dropwizard-guicey#43]
I'm looking for support for dropwizard 1.2.0. I see the changes are in master. Please release a newer version. Thanks

**Comment by xvik** [comment]
Hi!

There are no compatibility issues with 1.2.0. I did the last commit just to show that guicey is compatible (all tests pass). You can simply declare 1.2.0 dropwizard dependency manually in your project.

I prefer to release new versions when it's really required (with new features or compatibility/bug fixes).
