### ISSUE TITLE
hibernate 5.2.15 'hibernate.implicit_naming_strategy' and  'hibernate.physical_naming_strategy' not work

### ISSUE THREAD

**Issue by pipinet** [xvik/dropwizard-guicey#47]
database:
  driverClass: org.mariadb.jdbc.Driver
  user: root
  password:
  url: jdbc:mariadb://localhost:3306/test
  properties:
      charSet: UTF-8
      hibernate.dialect: org.hibernate.dialect.MariaDBDialect
      hibernate.hbm2ddl.auto: none
      hibernate.show_sql: true
      hibernate.jdbc.time_zone: UTC
      hibernate.dialect.storage_engine: innodb
      hibernate.connection.provider_class: org.hibernate.hikaricp.internal.HikariCPConnectionProvider
      hibernate.implicit_naming_strategy: bw.commons.hibernate.naming.StandardImplicitNamingStrategy(like spring ImplicitNamingStrategy)
      hibernate.physical_naming_strategy: bw.commons.hibernate.naming.StandardPhysicalNamingStrategy(like spring PhysicalNamingStrategy)

**Comment by xvik** [comment]
This is core dropwizard question (with no relation to guicey). You can ask it in dropwizard-user list: https://groups.google.com/forum/#!forum/dropwizard-user (or on stackoverflow).

I'm not using hibernate and so can't help you. I can only suggest to look hibernate bundle sources and debug it to see why strategy is not bound (it should be pretty easy to find).

**Comment by pipinet** [comment]
ok. thank you ....
i find the way to fix it.
in HibernateBundle  .. i can Override  configure function ...

@Override
    protected void configure(Configuration configuration) {
        configuration.setImplicitNamingStrategy(new StandardImplicitNamingStrategy());
        configuration.setPhysicalNamingStrategy(new StandardPhysicalNamingStrategy());
    }
