### ISSUE TITLE
hibernate 5.2.15 'hibernate.connection.provider_class' not work

### ISSUE THREAD

**Issue by pipinet** [xvik/dropwizard-guicey#48]
i config  properties in 

database-> properties

hibernate.connection.provider_class: org.hibernate.hikaricp.internal.HikariCPConnectionProvider

but hibernate connection provider do not use this provider

**Comment by xvik** [comment]
The same as previous, this is core dropwizard question (with no relation to guicey). You can ask it in dropwizard-user list: https://groups.google.com/forum/#!forum/dropwizard-user (or on stackoverflow).

Dropwizard is pretty tied to tomcat pool, but it is still possible to switch: [dropwizard-hikaricp](https://github.com/mtakaki/dropwizard-hikaricp). It is questionable if this switch [makes sense](https://nbsoftsolutions.com/blog/the-difficulty-of-performance-evaluation-of-hikaricp-in-dropwizard). If you don't have the real need (pool is not your bottleneck) I would suggest using the standard one (tomcat pool).

**Comment by pipinet** [comment]
ok.. thank you.
datasrouce allways start up before hibernate...
so i need use dropwizard-hikaricp....
thank you...
