### ISSUE TITLE
404 for resources when rootPath defined in yml

### ISSUE THREAD

**Issue by DrMattFaulkner** [xvik/dropwizard-guicey#5]
Hi,

With the following section defined in the server.yml I get a 404 for all resources. If I remove the rootPath and the resources work.

server:
  rootPath: '/api/v1'

  applicationConnectors:
      - type: http
        port: 8080
  adminConnectors:
      - type: http
        port: 8081

**Comment by xvik** [comment]
Hi,

Try
```
rootPath: '/api/v1/*'
```

**Comment by DrMattFaulkner** [comment]
Excellent!! That works. Thank you very much!

**Comment by xvik** [comment]
You're welcome :)
