### ISSUE TITLE
QUERY: Multiple DropwizardAware Modules?

### ISSUE THREAD

**Issue by nheitz** [xvik/dropwizard-guicey#52]
Hello!
Using Dropwizard 1.3.4 with guicey 4.1.0.  I realise that there is a newer guicey, and I will be testing that shortly.

Simple question....is it possible to have multiple guice modules, all of which are "DropwizardAware" in order to benefit from the configuration() and environment() methods?  A recent test seems ot suggest that only one of the modules get initialised with configuration and environment before all the have "configure()" executed on them, which is leading to an error.

**Comment by nheitz** [comment]
@xvik  Thanks for your quick response!
Ok, the issue has evolved now.

I am currently doing this
`        this.guiceBundle = GuiceBundle.<WorkflowServerConfiguration>builder()
                //.injectorFactory(new GovernatorInjectorFactory())
                .enableAutoConfig(AUTO_DISCOVERY_EXTENSION_PACKAGES)
                .modules(Modules.override(new RabbitMqModule()).with(new WorkflowServerModule()))
`
WorkflowServerModule extends DropwizardAwareModule, but the things like configuration and environment are not populated.

If I get rid of the Modules.overide(...), however, then those fields are populated.  This suggest to me that whatever is returned by guice when using Modules.override() (the same is true for Modules.combine()) is not handled by Guicey as far as dropwizard awareness.

**Comment by xvik** [comment]
Yes, exactly. *Aware markers are checked on directly registered modules (as `module instanceof`) so when you're using `Modules.override` you actually register different module class, not implementing marker interface.

Note that in 4.2.0 modules override is [directly supported](http://xvik.github.io/dropwizard-guicey/4.2.0/guide/configuration/#override-guice-bindings): modules() - normal modules and modulesOverride() - overriding modules. And both types could be "aware" of dropwizard objects.
(and there is even support for [overriding overridden](http://xvik.github.io/dropwizard-guicey/4.2.0/guide/test/#overriding-overridden-beans))

**Comment by xvik** [comment]
Yes, governator should work. I did not do any "magic" on guice level.  
I never used governator myself (even governator integration was contributed) and, honestly, don't see any profit from it (especially in context of dropwizard).

> has it also been retrofitted to support greater "awareness"?

I may not quite understand the question, but if its about some soecial governator support on guice level then no - custom factory only creates injector differently (in the "governator way").
