### ISSUE TITLE
Release 4.2.2

### ISSUE THREAD

**Issue by minisu** [xvik/dropwizard-guicey#55]
The Guice dependency was bumped to 4.2.2 (required for Java 11) a month ago, but there hasn't been a release of dropwizard-guicey since then. Are there any plans to release soon?

Thanks for a great project!

**Comment by xvik** [comment]
Honestly, I did not plan to release it soon as there are no actual features or important bug fixes.
I assume that users don't rely on transitive guice and dropwizard versions and manually specify the required versions.

But, you are right, I can release 4.2.2 to avoid confusion (will do today).

**Comment by minisu** [comment]
Thanks!

Yes, it's not hard to manually specify Guice 4.2.2 (but it requires some digging to find out why things breaks in the first place and that manually specifying Guice version won't break dropwizard-guicey).

**Comment by xvik** [comment]
[Released](https://github.com/xvik/dropwizard-guicey/releases/tag/4.2.2)
