### ISSUE TITLE
Field injection with @Config not working

### ISSUE THREAD

**Issue by tristan957** [xvik/dropwizard-guicey#56]
The values are null, but the printed configuration bindings say otherwise.

```yaml
Configuration paths bindings:

        AppConfiguration:
            @Config("graph") GraphConfiguration = io.r0s.fwf.config.GraphConfiguration@18adacad
            @Config("graph.host") String = "localhost"
            @Config("graph.password") String = "neo4j"
            @Config("graph.port") Integer = 7687
            @Config("graph.username") String = "neo4j
```

```java
// AppConfiguration.java
public final class AppConfiguration extends Configuration {
	@NotNull
	@JsonProperty("graph")
	private GraphConfiguration graphConfig;

	public GraphConfiguration getGraphConfig() {
		return this.graphConfig;
	}
}

// GraphConfiguration.java
public final class GraphConfiguration {
	@NotNull
	@JsonProperty
	private String host;

	@NotNull
	@JsonProperty
	private Integer port;

	@NotNull
	@JsonProperty
	private String username;

	@NotNull
	@JsonProperty
	private String password;

	public String getHost() {
		return this.host;
	}

	public int getPort() {
		return this.port;
	}

	public String getUsername() {
		return this.username;
	}

	public String getPassword() {
		return this.password;
	}
}

// initialize function
final Builder<AppConfiguration> builder = GuiceBundle.builder();
final GuiceBundle<AppConfiguration> guiceBundle = builder.enableAutoConfig(App.class.getPackage().getName())
	printConfigurationBindings().build();
bootstrap.addBundle(guiceBundle);

// field injection in Neo4jHealthCheck.java
@Inject
@Config("graph.host")
private String host;

@Inject
@Config("graph.port")
private Integer port;

@Inject
@Config("graph.username")
private String username;

@Inject
@Config("graph.password")
private String password;
```

These are the docs I am using http://xvik.github.io/dropwizard-guicey/4.2.2/concepts/#configuration-bindings

**Comment by xvik** [comment]
If "injected" values are null it almost certainly means no injection was performed. Please make sure that your health check is [managed by guicey](http://xvik.github.io/dropwizard-guicey/4.2.2/installers/healthcheck/): 
1. Check extends `NamedHealthCheck`
1. Check is not registered manually (and you should see it listed in console logs during startup (or with `.printDiagnosticInfo()`))
1. To be sure try to inject some other guice bean (service) - if it will be also null then check is not managed by guice.

**Comment by tristan957** [comment]
Ok I extended NamedHealthCheck instead. Now the check is managed by Guicey according to the diagnostic info.

```
APPLICATION
    ├── module     GuiceBootstrapModule         (r.v.d.guice.module)
    │
    ├── DiagnosticBundle             (r.v.d.g.m.c.debug)
    │   └── module     DiagnosticModule             (r.v.d.g.m.c.d.DiagnosticBundle)
    │
    ├── CoreInstallersBundle         (r.v.d.g.m.installer)
    │   ├── installer  ManagedInstaller             (r.v.d.g.m.i.feature)
    │   ├── installer  ResourceInstaller            (r.v.d.g.m.i.f.jersey)
    │   └── installer  HealthCheckInstaller         (r.v.d.g.m.i.f.health)
    │
    └── CLASSPATH SCAN
        ├── extension  Neo4jSessionFactory          (io.r0s.fwf.managed)
        ├── extension  UserResource                 (io.r0s.fwf.resources)
        ├── extension  GroupResource                (io.r0s.fwf.resources)
        └── extension  Neo4jHealthCheck             (io.r0s.fwf.health)
```
Unfortunately the fields are still null though. Do you have any other suggestions

**Comment by tristan957** [comment]
If you need any more logs, or want to see the source code please let me know

**Comment by xvik** [comment]
Yes, please share the source so I could reproduce it.

**Comment by xvik** [comment]
I looked at your code and I don't see the problem. 

Changes:

In main App class I add health check as an extension (because it's not covered by configured classpath scan):
```java
bootstrap.addBundle(GuiceBundle.builder()
				.enableAutoConfig(
						String.format("%s.resources", packageName), 
						String.format("%s.services", packageName))
				.extensions(Neo4jHealthCheck.class)
				.build());
```

And, of course, removed manual check registration:
```java
//environment.healthChecks().register("Neo4j", neo4jHealthCheck);
```

Health check itself:
```java
public final class Neo4jHealthCheck extends NamedHealthCheck {

	@Inject
	@Config("graph.host")
	private String host;

	@Override
	protected Result check() throws Exception {
              System.out.println(host+" ! "+port);
	      return host == null ? Result.unhealthy("no injection") : Result.healthy();
        }

        @Override
	public String getName() {
		return "neo4j";
	}
}
```

I suspect that you did not remove manual check registration when you tried yourself. In this case two health checks registered: one without injection (manually registered) and another installed by guicey with proper injection. And the result in this case would be (for my simplified health check):

```java
{
  "Neo4j" : {
    "healthy" : false,
    "message" : "no injection"
  },
  "deadlocks" : {
    "healthy" : true
  },
  "neo4j" : {
    "healthy" : true
  }
}
```

I always suggest to use constructor injection instead of filed injection:
```java
public final class Neo4jHealthCheck extends NamedHealthCheck {

        private String host;

	@Inject
	public Neo4jHealthCheck(@Config("graph.host") String host) {
		this.host = host;
	}
```
Because in this case it's impossible to create instance with the default (empty) constructor which will lead to inconsistent state (and confusion).

**Comment by tristan957** [comment]
@xvik thanks for taking a look. I think you may have pulled the master branch which didn't have the health check changes from earlier. I am going to try out the constructor injection which I have used on the past, and make sure that it works. I will leave the state of the issue up to you. I poured over your documentation left and right trying to find the answer. Is this possibly maybe an issue with Guice itself?

**Comment by xvik** [comment]
Mmm, yes, sorry I indeed checked master. 

Your problem is the constructor:
```java
public Neo4jHealthCheck() {
		this.client = ClientBuilder.newClient();
		this.url = String.format("http://%s:%d", this.host, this.port);
		log.info("URL: {}", this.url);
	}
```

Field injection will work after it so you will always have nulls in uri (you can debug health check and see that host and port are not null when the check is called). And you need constructor injection to solve this or initialize uri lazily (on first check execution).

**Comment by tristan957** [comment]
Understanding on my end of Guice in general. Still getting a hang of lifetimes. Thanks for your help. I ended up going with constructor injection because in the end that made more sense. Closing the issue  now.
