### ISSUE TITLE
Issue with @RequestScoped

### ISSUE THREAD

**Issue by akraxx** [xvik/dropwizard-guicey#6]
Hi,

I'm currently migrating my project from dropwizard-guice to dropwizard-guicey, and I have an issue with the @RequestScoped annotation :

I have a resource which injects a class bound in RequestScoped, when I run the dropwizard i have the following error :

1) Error in custom provider, com.google.inject.OutOfScopeException: Cannot access scoped [net.atos.itsm.library.database.DaoManager]. Either we are not currently inside an HTTP Servlet request, or you may have forgotten to apply com.google.inject.servlet.GuiceFilter as a servlet filter for this request.
  at dw.samples.database.jdbi.MyDatabaseModule.configureDatabase(MyDatabaseModule.java:70)
  while locating net.atos.itsm.library.database.DaoManager
    for parameter 0 at dw.samples.database.jdbi.MyDatabaseModule.providesCustomerDao(MyDatabaseModule.java:97)
  at dw.samples.database.jdbi.MyDatabaseModule.providesCustomerDao(MyDatabaseModule.java:97)
  while locating dw.samples.database.jdbi.dao.CustomerDao
    for parameter 0 at dw.samples.database.resources.CustomerResource.<init>(CustomerResource.java:33)
  at ru.vyarus.dropwizard.guice.module.installer.feature.jersey.ResourceInstaller.install(ResourceInstaller.java:44) (via modules: ru.vyarus.dropwizard.guice.module.GuiceSupportModule -> ru.vyarus.dropwizard.guice.module.installer.InstallerModule)
  while locating dw.samples.database.resources.CustomerResource

Did I miss something or we can't use this scope anymore?

**Comment by akraxx** [comment]
I resolved it by injecting a Provider of my DAO instead of the DAO directly. Maybe i'm wrong but I think it's because resource are injected as singleton, before a new instance was created for each new HTTP request, it has been changed for performance issues?

**Comment by xvik** [comment]
Hi,

You are right, resources are always registered as singletons (["Resources registered as singletons.."](https://github.com/xvik/dropwizard-guicey#resource)). I think its a waste of system resources to use prototype scope for rest (thousands of instances under high load .. and for what?).

If you need prototype scoped resources, you can always do your own installer and register it instead of the default.

By the way, all jersey extensions are also forced to be singletons (for the same reason).

**Comment by akraxx** [comment]
Seems great to me :) Thx for the answer!

**Comment by sirianni** [comment]
It seems like this is supported now [looking at the docs](https://xvik.github.io/dropwizard-guicey/4.2.2/installers/resource/)...?

```
.option(InstallerOptions.ForceSingletonForJerseyExtensions, false)
```

**Comment by xvik** [comment]
Yes, resources may not be singletons since 4.2.0.
This option changes the default behavior, but if you want to change scope only for a few resources, you can simply annotate them with `@RequestScoped` or `@Prototype` scoping annotations.
