### ISSUE TITLE
Support for Dropwizard 2.0.0

### ISSUE THREAD

**Issue by sdqali** [xvik/dropwizard-guicey#61]
Hello,

Thank you for the work you have done towards supporting Dropwizard 2.0.0. Now that the Dropwizard 2.0.0 milestone is [complete](https://github.com/dropwizard/dropwizard/milestone/18) and a release looks [imminent](https://groups.google.com/forum/#!topic/dropwizard-dev/2OqECMYwfow), I am wondering how close we are to a release that supports it.

I did some tests in my setup with Dropwizard 2.0.0-rc5 and [5ecb5caa975309dd5b7f2cef989bcf4939e35e85](https://github.com/xvik/dropwizard-guicey/commit/5ecb5caa975309dd5b7f2cef989bcf4939e35e85) and things seem to work.

Let me know if I can help test anything.

Thank you.

**Comment by xvik** [comment]
Hello!

Dropwizard 2.0 compatible guicey version is long time ready, but, as dropwizard did many breaking changes in 2.0 (actually jersey did) I decided to also do all long-delayed breaking changes on guicey side too (fix some conceptual mistakes). I am very close to finishing everything I want. I think it will take near 2 weeks to finish (including documentation update and examples check).

Also, this time, I want to publish a release candidate first in order to collect some feedback on breaking changes (and probably fix something, if required).

So, most likely it will go like this:
1. guicey RC1 in ~1-2w
2. guicey-ext RC1 in few days or week after
3. final release for both as soon as I receive positive feedback on changes

**Comment by xvik** [comment]
RC1 released: 'ru.vyarus:dropwizard-guicey:5.0.0-rc.1'

[Release Notes](http://xvik.github.io/dropwizard-guicey/5.0.0-rc.1/release-notes/) is currently the only actual docs page but should be enough.

NOTE: RC1 for guicey-ext is **not released yet**

Any feedback is welcomed! It's the last chance to correct anything before the final release.

**Comment by xvik** [comment]
**Guicey RC2** released: 'ru.vyarus:dropwizard-guicey:5.0.0-rc.2'
[Release notes](http://xvik.github.io/dropwizard-guicey/5.0.0-rc.2/release-notes/) as before the only actual documentation page. But it was improved (especially migration section).

Important changes:
* Targets dropwizard-2.0.0-rc10 (where bom package was split to bom and dependencies, jdbi module (old) moved to separate module)
* Updated hk2-bridge dependency
* In main GuiceBudle builder added uniqueItems() to easily mark unique modules or bundles without code changes

**Extensions RC1** released: 'ru.vyarus.guicey:guicey-bom:5.0.0-0-rc.1'

Important changes:
* Extensions version now aligned with guicey: guiceyVersion-Number (same pattern as for  dropwizard modules). It loose extensions semantic versioning, but target guicey will be more clear.
* All modules are guicey bundles now: SpaBundle, ServerPagesBundle. 
* ServerPagesBundle.extendApp() now also return bundle, which must be registered

No updated documentation yet.

**Examples** were also updated to released versions: https://github.com/xvik/dropwizard-guicey-examples

Most likely, there will be at least one more RC, but should be without breaking changes.
As usual, ANY feedback is welcomed! Including "not a problem, but could be better" kind.

**Comment by xvik** [comment]
Updated documentation [published](http://xvik.github.io/dropwizard-guicey/5.0.0-rc.2/). 
User guide section was almost completely rewriitten and heavily restructured to be easier to use.

RC3 will be released in a few weeks (as soon as it will be ready). The only planned breaking change is moving admin rest bundle to external modules. Other changes should be just improvements.

**Comment by xvik** [comment]
**Guicey RC3** released: 'ru.vyarus:dropwizard-guicey:5.0.0-rc.3'
**Extensions RC2** released: 'ru.vyarus.guicey:guicey-bom:5.0.0-0-rc.2'
Examples updated https://github.com/xvik/dropwizard-guicey-examples

[Full documentation](http://xvik.github.io/dropwizard-guicey/5.0.0-rc.3/)

Improratnt changes:

* Dropwizard 2.0.0-rc12
* Fix dropwizard bundles tracking
* `AdminRestBundle` moved to ext modules
* Remove generics from `GuiceBundle` and `FeatureInstaller` (useless generics)
* 2 new reports: web mappings and jersey configration
* Add injector static lookup by `Environment` object
* `@InvisibleForScanner` also prevents extension recognition from guice binding

**Comment by xvik** [comment]
Dropwizard released. I will release guicey in a week (probably this weekend).

**Comment by xvik** [comment]
5.0.0 released: see [release notes](http://xvik.github.io/dropwizard-guicey/5.0.0/about/release-notes/)

It is a huge release with big changes, hope migration will go well. It's a pity I did not receive any feedback about release candidates, hope it means that everyone tried it was happy :)

If you will have problems, don't hesitate to ask (here, gitter, google groups or directly by mail)
