### ISSUE TITLE
AutoDiscovery Using JerseyProviderInstaller appears to be double registering custom request and response filters.

### ISSUE THREAD

**Issue by nheitz** [xvik/dropwizard-guicey#7]
dropwizard-guicy-3.1.0
jersey-server-2.2.1
dropwizard-core-0.8.4

In trying to use the autodiscovery feature discover Request and Response filters by package:
bootstrap.addBundle(GuiceBundle.builder()
                .enableAutoConfig("com.business.filters")
                .modules(new GuiceModule())
                .build());

I've noticed that both Request and Response filters are fired twice for each http request.  Both my request and response filters are annotated with @Provider in order to facilitate the discovery.  After digging into the jersey / dropwizard code, it seems that the org.glassfish.jersey.internal.inject.Providers helper class is detecting duplicate Service Definitions for the custom filters...digging any further into that locator code is an exercise in madness.

This behaviour does not occur using manual registration:
environment.jersey().register(ContextProcessingRequestFilter.class);
environment.jersey().register(ContextProcessingResponseFilter.class);

This leads me to include that the issue resides either in the dropwizard guicey autodiscovery, or in the system's handling of the @Provider annotation.

**Comment by nheitz** [comment]
After further investigation, the code is behaving as expected.  What I didn't realise was that auto discovery recursed through subpackages as well, and I had added both child ands parent packages explicitly. 
This can be closed directly. ..maybe I can add a line to the readme describing this behaviour?

**Comment by xvik** [comment]
Glad to hear that it works finally :)
I always thought that its obvious about all subpackages, but if its not ofc you can improve the readme.
Probably possibility to define multiple packages is confusing, but it was done to allow substracting some paths (when root package can't be specified directly).

But, in general, it's still strange: duplicates should be avoided by guice because both extensions will be registered as singletons which should lead to just one object in runtime. 
I will check this behaviour.

**Comment by nheitz** [comment]
I think the issue is not to do with it being a singleton, bur the fact that jersey maintains its filters as a linked list, so if the same singleton gets added twice...well,it gets fired twice for a request.

I'm sure the recursion is obvious. ..my brain just misfired on it.

**Comment by xvik** [comment]
Yes, almost. Its ok on guice side but due to registration specifics (factory) jersey can't detect duplicate instance. 
I will add packages intercection check to avoid such cases in the future.
