### ISSUE TITLE
Support for JUnit 5

### ISSUE THREAD

**Issue by siwonred** [xvik/dropwizard-guicey#74]
Hello!
Thank you for your work 👍 

http://xvik.github.io/dropwizard-guicey/5.0.0/guide/test/
I saw that there is a plan to apply JUnit5 above the document, but our team still hopes to apply for it.

**Comment by xvik** [comment]
Hello! 

Yes, junit5 support is planned, but can't tell exactly when. 
Probably, in February or March, but not sure.

**Comment by syoh0708** [comment]
Our team is grateful for your help :)

**Comment by siwonred** [comment]
What a good news! Good work! Thank you!

**Comment by siwonred** [comment]
https://github.com/xvik/dropwizard-guicey/releases/tag/5.1.0
