### ISSUE TITLE
Clarify request scope transition 

### ISSUE THREAD

**Issue by zcmyth** [xvik/dropwizard-guicey#84]
I was trying to follow the example [here](https://github.com/xvik/dropwizard-guicey/blob/master/src/doc/docs/guide/guice/scopes.md#request-scope-transition) to transfer the request scope to a different thread. However, it doesn't work and I got error saying it is not in a request scope.

Then I found [this test  ](https://github.com/xvik/dropwizard-guicey/blob/c0da9a1a0fbda8a30da534d5e01d74116bfc98a5/src/test/groovy/ru/vyarus/dropwizard/guice/web/GuiceRequestScopePropagationTest.groovy#L60) which is very similar to the example but has 
```
// object must be resolved inside request hk scope so guice could use it's instance later
uri.get().getRequestUri()
```

I also find the comment [here](https://github.com/xvik/dropwizard-guicey/blob/399602172fd0c763af1caff9f4097bf500586c10/src/main/java/ru/vyarus/dropwizard/guice/module/jersey/hk2/GuiceBindingsModule.java#L90) warns 
```
WARNING: bean instance must be obtained in current (request) thread in order to be us used 
later inside transferred thread (simply call {@code provider.get()} (for jersey-managed bean 
like {@link UriInfo}) before {@code ServletScopes.transferRequest()}.
```

Does this mean the example is actually missing a line to obtain the uri in current thread?

**Comment by xvik** [comment]
Thank you! You are right, an additional call is of course required! The reason for it that guice could transit only known request-scoped objects to another thread, but, if the object was never obtained before, guice will call jersey which, of course, can't associate different thread with its request scope.

A simple call like `uri.get()` resolves object under hk request scope and put it into guice request scope, so it could be used within other threads.

[Documentation fixed](http://xvik.github.io/dropwizard-guicey/5.0.0/guide/guice/scopes/#request-scope-transition)

**Comment by zcmyth** [comment]
Thank you so much for the quick response 😊
