### ISSUE TITLE
Errors when configuration contains nested map with enums as keys

### ISSUE THREAD

**Issue by neVERberleRfellerER** [xvik/dropwizard-guicey#87]
I am migrating project to `dropwizard-guicey` as one of steps towards dropwizard 2 and I have some issues with nested map in configuration.

Having dropwizard `1.3.20` and `dropwiazrd-guicey` `4.2.2` and
```
private EnumMap<Enum1, EnumMap<Enum2, String>> someMap =
    new EnumMap<>(Enum1.class);
```
in configuration leads to
```
ru.vyarus.java.generics.resolver.error.UnknownGenericException: Generic 'K' (defined on EnumMap<K, V>) is not declared
```

Replacing with 

```
private Map<Enum1, Map<Enum2, String>> someMap = new HashMap<>();
```
leads to
```
java.lang.StackOverflowError
```
in
```
at ru.vyarus.dropwizard.guice.module.yaml.ConfigTreeBuilder.resolvePaths(ConfigTreeBuilder.java:195)
```

**Comment by xvik** [comment]
I will check and fix this for 5.x. 
You can [disable configuration introspection](http://xvik.github.io/dropwizard-guicey/4.2.2/guide/bindings/#disable-configuration-introspection) (on field or completely) to workaround problem.
