### ISSUE TITLE
Guice 4.2.3

### ISSUE THREAD

**Issue by emre-e** [xvik/dropwizard-guicey#91]
Hello!

Thank you for this great project :+1:

A new version of Guice (4.2.3) is released and it has Java14 support.

Are you planning to have a release that upgrades Guice from 4.2.2 to 4.2.3?

Thanks!

**Comment by xvik** [comment]
Hello!
Generally, I don't release a new version just to update dependencies (5.0.1 was an exception). I encourage everyone to use [boms](https://github.com/xvik/dropwizard-guicey#bom) so updating dependency would not be a problem (guice has a bom too):

```groovy
dependencyManagement {
    imports {
        mavenBom "ru.vyarus.guicey:guicey-bom:5.0.1-1"
        mavenBom "com.google.inject:guice-bom:4.2.3"
    }
}
```

I plan to release 5.1.0 with junit 5 extensions soon but can't tell exactly when.

**Comment by siwonred** [comment]
https://github.com/xvik/dropwizard-guicey/releases/tag/5.1.0 👍
