### ISSUE TITLE
Binding ExceptionMappers that override the dropwizard defaults is cumbersome

### ISSUE THREAD

**Issue by smorel-plenty** [xvik/dropwizard-guicey#97]
`dw:2.0.2, guicey:5.0.1, guice:4.2.2, jersey:2.30`

First, thank you for you great work on this project.

Overall, the crux of this feature request is to make guice-bound components installed via `JerseryProviderInstaller` behave more like components registered via `environment().jersey().register`

Repro case, I want to override the default `ExceptionMapper<Throwable>` without disabling all the dw default exception mappers. The recommended dropwizard usage is to leave the default exception mappers enabled and override them. I also want to just bind my custom mapper in a regular guice module and have it picked up by the JerseryProviderInstaller.

When you install an exception mapper via `environment().jersey().register(MyExceptionMapper.class);` it implicitly gets marked as `@Custom` and during lookup in `Providers.getAllServiceHolders()` is found by

```
        List<ServiceHolder<T>> providers = getServiceHolders(injectionManager,
                                                             contract,
                                                             Comparator.comparingInt(Providers::getPriority),
                                                             CustomAnnotationLiteral.INSTANCE);
```

which makes it the first in the list (ahead of the DW default). 

If you bind the custom `ExceptionMapper<Throwable>` via guice (even if you annotate your instance with `@Custom` or `@Priority` those annotations aren't propagated on the factory binding by `JerseryProviderInstaller` in `JerseyBinding#bindSpecificComponent`. 

A few options to make provider installer behave more like `jersey.register`

1) Make `JerseyProviderInstaller` just like `jerser.register`. My current understanding is that the provider installer runs to late to add a component to the common config component bag but that all those components get automatically registered as `@Custom`? 

2) If there's a `@Custom` or `@Priority` on an `@Provider` annotated class, the `JerseyBinder.bindSpecificComponent` could propagate them to the `bindFactory`.

**Comment by xvik** [comment]
Thank you! I didn't know that it is possible to override default exception mapper like this! 

Guicey register lazy factories (providers) which propagate guice-managed instance. And, of course, I did not propagate `@Custom` and `@Priority` markers (and hk2 looks them on actual target only).
It should be easy to add support for them (option 2).

About (1): `JerseyProviderInstaller` is not executed too late: it performs all registrations exactly at hk2 configuration time (the same as if you manually bind everything in hk2 BindingModule and register it through `jersey.register`).

I can't promise I'll do it too soon: need to do other things first, but should be part of 5.1.0 release (maybe in a month).

**Comment by smorel-plenty** [comment]
Just an FYI, if I had to vote between this and junit5 extensions, I'd pick junit5 :) This at least has an easy workaround, it was just surprising that the result was different for components bound via `JerseyProviderInstaller` to behave differently than through `jersey.register`

I have a very crude bit of code that writes a junit 5 extension that delegates all the work to a `GuiceyAppRule`. The pattern is inspired by how the misk framework does testing https://github.com/cashapp/misk/tree/master/misk-testing/src/main/kotlin/misk/testing

**Comment by xvik** [comment]
5.1.0 [released](http://xvik.github.io/dropwizard-guicey/5.1.0/about/release-notes/) with junit 5 extensions. 
The main issue will be fixed a bit later in the upcoming bugfix release

**Comment by xvik** [comment]
The new version would behave the same as raw dropwizard: `@Custom` qualification annotation assigned to all providers. But only for providers (I see no need to qualify resources).

`@Priority` is now also correctly supported. But there is a catch: priorities work differently with `@Custom` qualified and raw providers (there are physically different branches in jersey logic: for `@Custom` providers, the sorting order is ascending and for raw providers is descending (probably a bug, but there are already a lot of issues for sorting order in jersey github). Anyway, this should not bother anyone as qualified sorting is correct.

As this change could potentially affect application behavior (user providers become more prioritized) there is a way to disable it: `.option(InstallersOptions#PrioritizeJerseyExtensions, false)`. In this case, the behavior would be exactly as before (no auto qualification), but beans could be manually annotated with `@Custom` for prioritization. Also, `@Priority` will also work in this case.

**Comment by xvik** [comment]
[released](http://xvik.github.io/dropwizard-guicey/5.2.0/about/release-notes/)
